# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_invoice.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(655, 371)
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(25, 10, 10, 10)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.invoice_code_lineEdit = QtGui.QLineEdit(Dialog)
        self.invoice_code_lineEdit.setObjectName(_fromUtf8("invoice_code_lineEdit"))
        self.gridLayout.addWidget(self.invoice_code_lineEdit, 0, 3, 1, 1)
        self.invoice_num_lineEdit = QtGui.QLineEdit(Dialog)
        self.invoice_num_lineEdit.setObjectName(_fromUtf8("invoice_num_lineEdit"))
        self.gridLayout.addWidget(self.invoice_num_lineEdit, 0, 1, 1, 1)
        self.total_num_lineEdit = QtGui.QLineEdit(Dialog)
        self.total_num_lineEdit.setObjectName(_fromUtf8("total_num_lineEdit"))
        self.gridLayout.addWidget(self.total_num_lineEdit, 4, 1, 1, 1)
        self.total_num_cn_lineEdit = QtGui.QLineEdit(Dialog)
        self.total_num_cn_lineEdit.setEnabled(True)
        self.total_num_cn_lineEdit.setDragEnabled(True)
        self.total_num_cn_lineEdit.setObjectName(_fromUtf8("total_num_cn_lineEdit"))
        self.gridLayout.addWidget(self.total_num_cn_lineEdit, 4, 3, 1, 1)
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 4, 2, 1, 1)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.custom_name_comboBox = QtGui.QComboBox(Dialog)
        self.custom_name_comboBox.setObjectName(_fromUtf8("custom_name_comboBox"))
        self.gridLayout.addWidget(self.custom_name_comboBox, 3, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.invoice_detail_tableWidget = QtGui.QTableWidget(Dialog)
        self.invoice_detail_tableWidget.setRowCount(1)
        self.invoice_detail_tableWidget.setObjectName(_fromUtf8("invoice_detail_tableWidget"))
        self.invoice_detail_tableWidget.setColumnCount(6)
        item = QtGui.QTableWidgetItem()
        self.invoice_detail_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.invoice_detail_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.invoice_detail_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.invoice_detail_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.invoice_detail_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.invoice_detail_tableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout_3.addWidget(self.invoice_detail_tableWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.add_invoice_detail_btn = QtGui.QPushButton(Dialog)
        self.add_invoice_detail_btn.setObjectName(_fromUtf8("add_invoice_detail_btn"))
        self.horizontalLayout.addWidget(self.add_invoice_detail_btn)
        self.del_invoice_detail_btn = QtGui.QPushButton(Dialog)
        self.del_invoice_detail_btn.setObjectName(_fromUtf8("del_invoice_detail_btn"))
        self.horizontalLayout.addWidget(self.del_invoice_detail_btn)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.reviewer_lineEdit = QtGui.QLineEdit(Dialog)
        self.reviewer_lineEdit.setObjectName(_fromUtf8("reviewer_lineEdit"))
        self.gridLayout_2.addWidget(self.reviewer_lineEdit, 0, 6, 1, 1)
        self.beneficiary_lineEdit = QtGui.QLineEdit(Dialog)
        self.beneficiary_lineEdit.setObjectName(_fromUtf8("beneficiary_lineEdit"))
        self.gridLayout_2.addWidget(self.beneficiary_lineEdit, 0, 4, 1, 1)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 3, 1, 1)
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 5, 1, 1)
        self.drawer_comboBox = QtGui.QComboBox(Dialog)
        self.drawer_comboBox.setObjectName(_fromUtf8("drawer_comboBox"))
        self.gridLayout_2.addWidget(self.drawer_comboBox, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.custom_name_comboBox, self.invoice_detail_tableWidget)
        Dialog.setTabOrder(self.invoice_detail_tableWidget, self.beneficiary_lineEdit)
        Dialog.setTabOrder(self.beneficiary_lineEdit, self.reviewer_lineEdit)
        Dialog.setTabOrder(self.reviewer_lineEdit, self.buttonBox)
        Dialog.setTabOrder(self.buttonBox, self.invoice_num_lineEdit)
        Dialog.setTabOrder(self.invoice_num_lineEdit, self.invoice_code_lineEdit)
        Dialog.setTabOrder(self.invoice_code_lineEdit, self.total_num_cn_lineEdit)
        Dialog.setTabOrder(self.total_num_cn_lineEdit, self.total_num_lineEdit)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "编辑发票信息", None))
        self.label.setText(_translate("Dialog", "发票号码", None))
        self.label_8.setText(_translate("Dialog", "发票代码", None))
        self.label_3.setText(_translate("Dialog", "合计金额", None))
        self.label_7.setText(_translate("Dialog", "金额大写", None))
        self.label_2.setText(_translate("Dialog", "客户名称", None))
        item = self.invoice_detail_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "ID", None))
        item = self.invoice_detail_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "商品代码", None))
        item = self.invoice_detail_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "品名", None))
        item = self.invoice_detail_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "数量", None))
        item = self.invoice_detail_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "单价", None))
        item = self.invoice_detail_tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "金额", None))
        self.add_invoice_detail_btn.setText(_translate("Dialog", "添加一列", None))
        self.del_invoice_detail_btn.setText(_translate("Dialog", "删除", None))
        self.label_5.setText(_translate("Dialog", "开票人", None))
        self.label_6.setText(_translate("Dialog", "收款人", None))
        self.label_4.setText(_translate("Dialog", "复核人", None))

