# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(521, 425)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("image/app.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_0 = QtGui.QWidget()
        self.tab_0.setStyleSheet(_fromUtf8(""))
        self.tab_0.setObjectName(_fromUtf8("tab_0"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_0)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(1)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.selectAllButton = QtGui.QPushButton(self.tab_0)
        self.selectAllButton.setInputMethodHints(QtCore.Qt.ImhNone)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("image/023.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.selectAllButton.setIcon(icon1)
        self.selectAllButton.setIconSize(QtCore.QSize(16, 16))
        self.selectAllButton.setAutoRepeat(False)
        self.selectAllButton.setObjectName(_fromUtf8("selectAllButton"))
        self.horizontalLayout.addWidget(self.selectAllButton)
        self.filterButton = QtGui.QPushButton(self.tab_0)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("image/010.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filterButton.setIcon(icon2)
        self.filterButton.setObjectName(_fromUtf8("filterButton"))
        self.horizontalLayout.addWidget(self.filterButton)
        self.genInvoiceButton = QtGui.QPushButton(self.tab_0)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("image/006.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.genInvoiceButton.setIcon(icon3)
        self.genInvoiceButton.setObjectName(_fromUtf8("genInvoiceButton"))
        self.horizontalLayout.addWidget(self.genInvoiceButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setMargin(1)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.tab_0)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.excelFilePathEdit = QtGui.QLineEdit(self.tab_0)
        self.excelFilePathEdit.setObjectName(_fromUtf8("excelFilePathEdit"))
        self.horizontalLayout_2.addWidget(self.excelFilePathEdit)
        self.selectExcelFileButton = QtGui.QPushButton(self.tab_0)
        self.selectExcelFileButton.setObjectName(_fromUtf8("selectExcelFileButton"))
        self.horizontalLayout_2.addWidget(self.selectExcelFileButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.excelTableWidget = QtGui.QTableWidget(self.tab_0)
        self.excelTableWidget.setRowCount(2)
        self.excelTableWidget.setColumnCount(8)
        self.excelTableWidget.setObjectName(_fromUtf8("excelTableWidget"))
        item = QtGui.QTableWidgetItem()
        self.excelTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.excelTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.excelTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.excelTableWidget.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.excelTableWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("image/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_0, icon4, _fromUtf8(""))
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_1)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tabWidget.addTab(self.tab_1, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 521, 23))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu_file = QtGui.QMenu(self.menuBar)
        self.menu_file.setObjectName(_fromUtf8("menu_file"))
        self.menu_config = QtGui.QMenu(self.menuBar)
        self.menu_config.setObjectName(_fromUtf8("menu_config"))
        self.menu_help = QtGui.QMenu(self.menuBar)
        self.menu_help.setObjectName(_fromUtf8("menu_help"))
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.menu_file.addAction(self.actionOpen)
        self.menu_file.addAction(self.actionClose)
        self.menuBar.addAction(self.menu_file.menuAction())
        self.menuBar.addAction(self.menu_config.menuAction())
        self.menuBar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "发票开具系统", None))
        self.selectAllButton.setText(_translate("MainWindow", "全选", None))
        self.filterButton.setText(_translate("MainWindow", "筛选", None))
        self.genInvoiceButton.setText(_translate("MainWindow", "生成发票", None))
        self.label.setText(_translate("MainWindow", "文件", None))
        self.selectExcelFileButton.setText(_translate("MainWindow", "选择", None))
        item = self.excelTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "测试1", None))
        item = self.excelTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "测试2", None))
        item = self.excelTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "新建列", None))
        item = self.excelTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "测试4", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_0), _translate("MainWindow", "数据导入", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "临时待处理数据", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "已开发票", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "客户管理", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "商品管理", None))
        self.menu_file.setTitle(_translate("MainWindow", "文件", None))
        self.menu_config.setTitle(_translate("MainWindow", "配置", None))
        self.menu_help.setTitle(_translate("MainWindow", "帮助", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionOpen.setText(_translate("MainWindow", "打开", None))
        self.actionClose.setText(_translate("MainWindow", "关闭", None))

